spring.application.name=budgetapp

# Changed localhost to 'db' (the name of the container in docker-compose)
spring.datasource.url=jdbc:mysql://db:3306/budgetdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Yash@123

# This helps Hibernate if it still struggles to guess the dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

jwt.secret=mysupersecretkeymysupersecretkey123456789012
jwt.expiration=900000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true